config:
  type: aws-parameterstore:/config/spring/

spring:
  #yaml
  config:
    import: ${config.type}
  #kakao
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: http://localhost:8080/{action}/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  token:
    secret-key: ${jwt.secret-key}
  access-token:
    expire-time: 1800000

cors:
  frontend: http://localhost:3000